[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🚀 节点选择,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/PlayStore.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/adobe.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/IDM.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/ai.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Copilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/GithubCopilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Claude.list
ruleset=☁️ CloudFlareCDN,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/CloudflareCIDR.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/Emby.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/direct.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=☁️ CloudFlareCDN,[]GEOIP,cloudflare
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📶 官方优选`load-balance`(官方|防|电信|联通|移动|CT|CU|CM|CF|t.me|WARP|Warp|warp)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🤖 OpenAi`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT`(NF|奈飞|解锁|Netflix|NETFLIX|Media|MITM)
custom_proxy_group=📺 巴哈姆特`select`[]🇯🇵 日本节点`[]🚀 节点选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇯🇵 日本节点`[]🇰🇷 韩国节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换`[]DIRECT`(MITM|emby|Emby)
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]☑️ 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇮🇩 印尼节点`[]🇳🇱 荷兰节点`[]🇲🇴 澳门节点`[]🇲🇾 马来西亚节点`[]🇸🇪 瑞典节点`[]🇵🇱 波兰节点`[]🇫🇮 芬兰节点`[]🇬🇧 英国节点`[]🇨🇳 中国节点`[]🇦🇹 奥地利节点`[]🇮🇳 印度节点`[]🇱🇻 拉脱维亚节点`[]📶 官方优选`[]☑️ 手动切换
custom_proxy_group=☁️ CloudFlareCDN`select`[]🐟 漏网之鱼`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]☑️ 手动切换
custom_proxy_group=🇯🇵 日本节点`url-test`(JP|JPN|Japan|Japanese|日本|川日|泉日|沪日|滬日|深日|东京|東京|大阪|京都|名古屋|横滨|橫濱|埼玉|福冈|福岡|札幌|冲绳|沖繩|Tokyo|Osaka|NRT|HND|KIX|ITM|NGO|FUK|CTS|OKA)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(US|USA|United States|UnitedStates|America|American|美国|美國|美西|美东|美東|波特兰|波特蘭|达拉斯|達拉斯|俄勒冈|俄勒岡|凤凰城|鳳凰城|费利蒙|費利蒙|硅谷|矽谷|拉斯维加斯|拉斯維加斯|洛杉矶|洛杉磯|圣何塞|聖何塞|圣克拉拉|聖克拉拉|西雅图|西雅圖|芝加哥|纽约|紐約|华盛顿|華盛頓|亚特兰大|亞特蘭大|迈阿密|邁阿密|丹佛|波士顿|波士頓|休斯敦|Atlanta|Boston|Chicago|Dallas|Denver|Houston|Las Vegas|Los Angeles|Miami|New York|Portland|San Jose|Seattle|Washington|ATL|BOS|BUF|DFW|DEN|EWR|IAD|IAH|JFK|LAS|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SFO|SJC)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|KOR|Korea|Korean|South Korea|韩国|韓國|韩|韓|首尔|首爾|春川|仁川|釜山|济州|濟州|Seoul|Incheon|Busan|Jeju|ICN|GMP|PUS|CJU)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(DE|DEU|Germany|German|Deutschland|德国|德國|柏林|法兰克福|法蘭克福|慕尼黑|杜塞尔多夫|杜塞爾多夫|汉堡|漢堡|Berlin|Frankfurt|Munich|Dusseldorf|Hamburg|BER|FRA|MUC|DUS|HAM|CGN|STR)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(HK|HKG|Hong Kong|HongKong|hongkong|香港|港岛|港島|九龙|九龍|新界)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(TW|TWN|Taiwan|台湾|台灣|台北|新北|桃园|桃園|台中|台南|高雄|彰化|Taipei|Taoyuan|Taichung|Kaohsiung|TPE|TSA|RMQ|KHH)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(SG|SGP|Singapore|新加坡|狮城|獅城|星加坡|坡县|坡縣|樟宜|Changi|SIN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇩 印尼节点`url-test`(ID|Indonesia|Indonesian|印尼|印度尼西亚|雅加达|巴厘岛|泗水|CGK|DPS|SUB)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇳🇱 荷兰节点`url-test`(NL|Netherlands|Nederland|Holland|荷兰|荷蘭|阿姆斯特丹|鹿特丹|AMS|RTM|EIN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门节点`url-test`(MO|Macao|Macau|澳门|澳門|MFM)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇾 马来西亚节点`url-test`(MY|Malaysia|马来西亚|馬來西亞|大马|吉隆坡|槟城|檳城|新山|亚庇|KUL|PEN|JHB|BKI)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇪 瑞典节点`url-test`(SE|Sweden|Swedish|瑞典|斯德哥尔摩|斯德哥爾摩|哥德堡|马尔默|馬爾默|ARN|BMA|GOT|MMX)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇵🇱 波兰节点`url-test`(PL|Poland|Polish|波兰|波蘭|华沙|華沙|克拉科夫|格但斯克|WAW|WMI|KRK|GDN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇫🇮 芬兰节点`url-test`(FI|Finland|Finnish|芬兰|芬蘭|赫尔辛基|赫爾辛基|HEL|TMP|TKU)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(GB|UK|United Kingdom|Great Britain|Britain|England|英国|英國|伦敦|倫敦|曼彻斯特|曼徹斯特|爱丁堡|愛丁堡|LHR|LGW|STN|LTN|LCY|MAN|EDI|BHX)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 中国节点`url-test`(CN|China|中国|中國|大陆|大陸|北京|上海|广州|廣州|深圳|成都|重庆|重慶|杭州|南京|武汉|武漢|西安|PEK|PKX|PVG|SHA|CAN|SZX|CTU|TFU|CKG|HGH|NKG|WUH|XIY)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇹 奥地利节点`url-test`(AT|Austria|Austrian|奥地利|奧地利|维也纳|維也納|萨尔茨堡|薩爾茨堡|因斯布鲁克|因斯布魯克|VIE|SZG|INN|GRZ)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度节点`url-test`(IN|India|Indian|印度|新德里|孟买|孟買|班加罗尔|班加羅爾|金奈|海得拉巴|加尔各答|加爾各答|DEL|BOM|BLR|MAA|HYD|CCU)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇱🇻 拉脱维亚节点`url-test`(LV|Latvia|Latvian|拉脱维亚|拉脫維亞|里加|RIX|LPX|VNT)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
